INSERT INTO maker(id, name) VALUES(1, 'Asus');
INSERT INTO maker(id, name) VALUES(2, 'Lenovo');
INSERT INTO maker(id, name) VALUES(3, 'Hewlett-Packard');
INSERT INTO maker(id, name) VALUES(4, 'Samsung');
INSERT INTO maker(id, name) VALUES(5, 'Seagate');
INSERT INTO maker(id, name) VALUES(6, 'Crucial');
INSERT INTO maker(id, name) VALUES(7, 'Gigabyte');
INSERT INTO maker(id, name) VALUES(8, 'Huawei');
INSERT INTO maker(id, name) VALUES(9, 'Xiaomi');

INSERT product(id, name, price, id_maker) VALUES(1, "Disco duro Sata3 1TB", 89.99, 5);
INSERT product(id, name, price, id_maker) VALUES(2, "Memoria RAM DDR4 8GB", 120, 6);
INSERT product(id, name, price, id_maker) VALUES(3, "Disco SSD 1 TB", 150.99, 4);
INSERT product(id, name, price, id_maker) VALUES(4, "Geforce GTX 1080 1050Ti", 185, 7);
INSERT product(id, name, price, id_maker) VALUES(5, "Geforce GTX 1080 Xtreme", 755, 6);
INSERT product(id, name, price, id_maker) VALUES(6, "Monitor 24 Led Full HD", 202, 1);
INSERT product(id, name, price, id_maker) VALUES(7, "Monitor 27 Led Full HD", 245.99, 1);
INSERT product(id, name, price, id_maker) VALUES(8, "Portátil Yoga 520", 559, 2);
INSERT product(id, name, price, id_maker) VALUES(9, "Portátil Ideapd 320", 444, 2);
INSERT product(id, name, price, id_maker) VALUES(10, "Impresora HP DeskJet 3720", 59.99, 3);
INSERT product(id, name, price, id_maker) VALUES(11, "Impresora HP LaserJet Pro M26nw", 180, 3);